/*
 * Words that must never appear in an ID vocabulary list.
 *
 * IDs are built as `${adjective}-${noun}` from src/assets/adjectives.ts and src/assets/nouns.ts. With a CSPRNG
 * picking each half independently, every possible pairing will eventually be produced and shown to a real person,
 * so a word is unsafe here if ANY plausible pairing of it is offensive -- not only if the word is offensive alone.
 * "black", "white" and "death" are each perfectly ordinary in isolation; "black-death" and "white-black" are not.
 * That is why neutral-looking words appear below, and why judgement is applied to the pairing rather than the word.
 *
 * The words currently in the vocabulary lists have already been removed from them. The rest of this set is a guard
 * against future additions: __tests__/unit/assets/excluded-id-words.test.ts fails if any word here is added back.
 */

export const excludedIdWords: Set<string> = new Set([
  // Identity: race, ethnicity, nationality, religion, gender, sexual orientation, immigration status.
  // A pejorative adjective plus a group label reads as a slur about the group rather than as an insult to a person,
  // and color words in the adjective slot ("black-", "white-", "brown-", "yellow-", "red-") read racially.
  'american',
  'arab',
  'asian',
  'black',
  'brown',
  'chink',
  'christian',
  'coon',
  'dusky',
  'dyke',
  'english',
  'faggot',
  'french',
  'fruity',
  'gender',
  'german',
  'gook',
  'gypsy',
  'hebrew',
  'hindu',
  'holy',
  'islam',
  'jew',
  'jewish',
  'kike',
  'mexican',
  'muslim',
  'nazi',
  'negro',
  'nigger',
  'oriental',
  'paki',
  'race',
  'racial',
  'red',
  'redskin',
  'refugee',
  'slope',
  'spanish',
  'spic',
  'squaw',
  'straight',
  'tranny',
  'wetback',
  'white',
  'yellow',

  // Political identity. Not a protected class, but "lousy-democrat" is an insult handed to a stranger.
  'conservative',
  'democrat',
  'fascist',
  'republican',
  'tory',

  // Violence and weapons.
  'assault',
  'blood',
  'bomb',
  'genocide',
  'grenade',
  'gun',
  'holocaust',
  'kill',
  'killer',
  'knife',
  'massacre',
  'missile',
  'molest',
  'murder',
  'pistol',
  'rape',
  'rifle',
  'shotgun',
  'slaughter',
  'slave',
  'slavery',
  'terrorist',
  'torture',
  'weapon',

  // Death and serious illness.
  'aids',
  'cancer',
  'casualty',
  'corpse',
  'dead',
  'deadly',
  'death',
  'disease',
  'ebola',
  'execution',
  'funeral',
  'grave',
  'hiv',
  'ill',
  'illness',
  'infection',
  'morgue',
  'mortality',
  'plague',
  'sick',
  'sickly',
  'suicide',
  'tumor',

  // Disability, mental health, and pejoratives about the mind.
  'blind',
  'crazy',
  'cripple',
  'crippled',
  'daft',
  'deaf',
  'depression',
  'disability',
  'disabled',
  'dotty',
  'dumb',
  'gimp',
  'handicap',
  'idiot',
  'imbecile',
  'insane',
  'lame',
  'loony',
  'lunatic',
  'mad',
  'midget',
  'moron',
  'psycho',
  'retard',
  'retarded',
  'spastic',
  'stupid',

  // Body and appearance pejoratives.
  'chunky',
  'dowdy',
  'dumpy',
  'fat',
  'fatty',
  'fleshy',
  'grotesque',
  'hideous',
  'homely',
  'obese',
  'plump',
  'skinny',
  'ugly',

  // General-purpose insults. Harmless against an object, degrading against every person noun in the list.
  'filthy',
  'foul',
  'vile',

  // Profanity.
  'bloody',
  'bugger',
  'damn',
  'hell',

  // Drugs.
  'cocaine',
  'crack',
  'dope',
  'drug',
  'heroin',
  'meth',

  // Sexual and excretory.
  'arse',
  'ass',
  'bastard',
  'bitch',
  'cock',
  'cunt',
  'dick',
  'fuck',
  'hole',
  'horny',
  'hot',
  'incest',
  'naked',
  'nude',
  'orgasm',
  'penis',
  'piss',
  'porn',
  'prostitute',
  'pussy',
  'semen',
  'sexy',
  'shit',
  'sleazy',
  'slut',
  'throat',
  'turd',
  'vagina',
  'wet',
  'whore',
])
